### ISSUE TITLE
Got an easy one for you.

### ISSUE THREAD

**Issue by NineDivinez** [pWn3d1337/Techguns#10]
I am having trouble trying to figure out how to use the oxygen mask.  I assumed it would allow for under water breathing, as there is already a gas mask, but seeing as that doesn't seem to be the case, I have no idea.  I checked the controls and there's no button to activate it either.  I also tried searching your wiki, but there isn't even a reference to it yet.  Think you can explain what it does?

**Comment by pWn3d1337** [comment]
It gives you underwating breathing, but you also need to wear oxygen tanks on your back. Some helmets already have builtin oxygen masks.

**Comment by NineDivinez** [comment]
AH ok, thank you very much :)
