### ISSUE TITLE
How do I power a turret?

### ISSUE THREAD

**Issue by COmmanderDerp999** [pWn3d1337/Techguns#101]
How do I power a turret?

**Comment by pWn3d1337** [comment]
By anything that provides RF, or you disable power requirement in config.

**Comment by guitargamer1** [comment]
What provides rf

**Comment by ilikememes123** [comment]
mine says i need F.E.

**Comment by colin15523** [comment]
you remove that config(I don't have it at least), and provided no direct answer on what produces RF or FE

**Comment by NeurospawN** [comment]
e
