### ISSUE TITLE
Game Keeps Crashing Please Help!

### ISSUE THREAD

**Issue by ghost** [pWn3d1337/Techguns#102]
When ever it says 2/7 my game always crashed and says this:
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: techguns/items/OreClusterScanner

Can someone please help me fix this?
Thanks,
PixelatedShadowYT

**Comment by ghost** [comment]
The version of the mod is 1.1.3

**Comment by pWn3d1337** [comment]
Required mods missing, Chisel and Cofhlib are required, read the post about requirements.
