### ISSUE TITLE
Minetweaker3

### ISSUE THREAD

**Issue by navaroneee** [pWn3d1337/Techguns#105]
Hello everyone 
I will print the error, MT dont recognizes Techguns
![mt](https://user-images.githubusercontent.com/24437327/30985843-faf1e6c8-a467-11e7-8fb2-f3d827ea3585.png)

**Comment by pWn3d1337** [comment]
show me your minetweaker script

**Comment by navaroneee** [comment]
pWn3d1337 tnks for reply, my mistake, i used a 1.1.3 STABLE version for Techguns, in my head 1.1.3 > 1.1.2Alpha, my bad, u can close this post

**Comment by pWn3d1337** [comment]
Yes, minetweaker support is only in the alpha, but don't think they are less stable, actually they should be more stable.

**Comment by navaroneee** [comment]
I've install it and like so much the new weapons too, tnks pWn3d1337
