### ISSUE TITLE
Ore drills cause crashes

### ISSUE THREAD

**Issue by masterofsomething321** [pWn3d1337/Techguns#117]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: techguns/blocks/machines/OreDrillBlock

version 1.1.3

please fix it, i cant even start the game. it crashes while loading

**Comment by pWn3d1337** [comment]
chisel is missing, read post about required mods.
