### ISSUE TITLE
Please fix this

### ISSUE THREAD

**Issue by Thatlonerkid** [pWn3d1337/Techguns#118]
whenever I try to play the game with the mod and addons properly installed, the game crashes. I have tried different downloads but they all lead me to this same one. Please fix this .

**Comment by pWn3d1337** [comment]
If it crashes you don't have chisel, an incorrect version of chisel or no cofhlib.

**Comment by Thatlonerkid** [comment]
ooooooooohhhhhhhhhh thanks!
