### ISSUE TITLE
charging station is bugged when it's drained

### ISSUE THREAD

**Issue by LordHellscream** [pWn3d1337/Techguns#119]
Minecraft 1.12.2
Techgun 2.0.1.0

Place some kind of early game power generator next to the charging station to charge it, and place a stack of empty energy cell in there. the power in the charging station drains out quickly, and it become bugged, the charging will never finish no matter how long it charges.

**Comment by pWn3d1337** [comment]
Moved to 1.12 issue tracker

https://github.com/pWn3d1337/Techguns2/issues/6
