### ISSUE TITLE
[Request] config to disable recipes

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [pWn3d1337/Techguns#125]
Currently (latest 1.7.10 version) you can make oil and plastic in the chemical laboratory. I would like a config option to disable these because they break GT5U's progression.

**Comment by pWn3d1337** [comment]
https://github.com/pWn3d1337/Techguns/wiki/Minetweaker-Support

you can remove/add recipes with minetweaker

**Comment by bHXDgiuMa5yLHyC8** [comment]
Thanks, I didn't know TG's machines had MT support.
