### ISSUE TITLE
Server crash - ReportedException: Exception ticking world

### ISSUE THREAD

**Issue by ProsperCraft** [pWn3d1337/Techguns#128]
Console showing stacktrace and right before it.
https://gist.github.com/ProsperCraft/45769a42049671b0878df1a35ec86c19

Crash report- 
https://paste.fedoraproject.org/paste/wHqSnH5YKtsv5s7aVCcIMA

techguns-1.12.2-2.0.1.1
forge-1.12.2-14.23.1.2601-universal

**Comment by ProsperCraft** [comment]
Another crash - https://paste.fedoraproject.org/paste/smFr2hFwGrGmUlrLsqRmbQ

**Comment by pWn3d1337** [comment]
None of this crash logs has a reference to techguns.
