### ISSUE TITLE
This isn't a bug. I'm just confused

### ISSUE THREAD

**Issue by Stryder914** [pWn3d1337/Techguns#13]
Can you give me some images of the multiblocks, I'm new to this crud, and I need a bit of help to learn my way around.

**Comment by pWn3d1337** [comment]
https://github.com/pWn3d1337/Techguns/wiki/Multiblock-Machines

https://github.com/pWn3d1337/Techguns/wiki/Ore-Drills

**Comment by Stryder914** [comment]
Can you also give me the site for the recipes for all the items and tools?

**Comment by pWn3d1337** [comment]
There is none, look them up in NEI.
