### ISSUE TITLE
Mekanism Tank Glitch

### ISSUE THREAD

**Issue by Stryder914** [pWn3d1337/Techguns#14]
I'm trying to use the reactor multiblock, but the Mekanism tanks won't drain the fluids into the reactor. Is there a specific mod to use, or am i setting it up incorrectly?

**Comment by pWn3d1337** [comment]
Mekanism pipes do work. The Reaction chamber does not let liquid in until you set the liquid level higher than 0. To drain liquid out you must lower the liquid level.

**Comment by Stryder914** [comment]
Well, THEY SHOULD, but they aren't. I set it to 50 and it still won't drain the fluids into the reactor.

**Comment by pWn3d1337** [comment]
can you post a screenshot of your setup, tank, pipes and reaction chamber, I think you do something wrong.

**Comment by Stryder914** [comment]
I'll try to, brb, expect it within a few hours.

**Comment by Stryder914** [comment]
nvm i figured it out
