### ISSUE TITLE
[BUG]Can't reload Gauss Rifle

### ISSUE THREAD

**Issue by BuckTheWeasel** [pWn3d1337/Techguns#140]
Gauss Rifle won't reload i have Energy Cells in my inventory.

Forge Version : 14.23.1.2594
Mc Version : 1.12.2
Mod Version : techguns-1.12.2-2.0.1.1

**Comment by Krid3l** [comment]
Hello there,

You need **Gauss Rifle Slugs** (if I remember their name correctly) to reload your Gauss Rifle - Its ammunition is not Energy Cells.

**Comment by pWn3d1337** [comment]
You need both slugs and the energy cell.
