### ISSUE TITLE
Fabricator Recipe requires Cybernetic Parts

### ISSUE THREAD

**Issue by chareon** [pWn3d1337/Techguns#15]
The fabricator housing looks to require cybernetic parts, which are only made in said fabricator. Is this a bug or are the first cybernetic parts supposed to be found in loot chests?

**Comment by pWn3d1337** [comment]
They drop from cyberdemons in the nether.

And the helicopter drops them too currently, but that might change in the future.

**Comment by chareon** [comment]
Good to know. Thanks.
