### ISSUE TITLE
missing Gun and other textures in JEI

### ISSUE THREAD

**Issue by IchigoGames** [pWn3d1337/Techguns#151]
First off i Really like the mod and would like to use it in a new modpack I'm working on but i really wish the guns did not have missing textures in jei

Minecraft 1.12.2
Forge 2624
techguns-1.12.2-2.0.1.1
jei_1.12.2-4.8.5.147
also tested with
jei_1.12.2-4.8.5.159

screenshot https://imgur.com/a/fiJ7W
https://imgur.com/6C92g52

**Comment by pWn3d1337** [comment]
This is a problem with other mods interfering with my rendering ASM code. I know of "Eleccore" being incompatible.

**Comment by IchigoGames** [comment]
ah ok thanks for the info i had that mod in my pack for Deep Resonance but its not a mod i have to have so ill try it without.

**Comment by IchigoGames** [comment]
ok that worked

**Comment by pWn3d1337** [comment]
Eleccore completely replaces a method I need to hook in for rendering, I can't really do something about it.
