### ISSUE TITLE
Loot has blank NBT tag

### ISSUE THREAD

**Issue by Landstryder** [pWn3d1337/Techguns#163]
It seem that every bit of loot from chests or the mob drop in this mod have a blank NBT tag. The only reason this is an issue is that they won't stack with any normally collected items you might have laying around, making it impossible to insert them into drawers filled with the same items and generally just taking up more space in your chests than necessary.

**Comment by ghost** [comment]
I have the same problem, maybe with CraftTweaker we can remove these tags?
Here's some screenshot of the problem
![nbt](https://user-images.githubusercontent.com/5892122/38158404-075c6e1c-3494-11e8-9c17-74dd2cc0bb1c.PNG)
![gg](https://user-images.githubusercontent.com/5892122/38158409-1fd02da8-3494-11e8-9af9-8db400467040.PNG)

**Comment by CanineCraver** [comment]
I'm having the same problem, it is somewhat annoying, this is just the alpha version for 1.12 so hopefully they'll be fixed in the future.
