### ISSUE TITLE
Cant Make Cybernetic Parts

### ISSUE THREAD

**Issue by IchigoGames** [pWn3d1337/Techguns#165]
how do you make Cybernetic Parts it looks like to make it you need a fabricator to make that you need fabricator housing to make that you need Cybernetic Parts [infinite loop]

techguns-1.12.2-2.0.1.1

**Comment by bHXDgiuMa5yLHyC8** [comment]
They drop from cyber demons and the attack helicopters that spawn after destroying a military base.

**Comment by IchigoGames** [comment]
well it makes it look like you need to craft them may want to included some kind of msg about how to get them.
