### ISSUE TITLE
You're wiki is very outdated.  I need the recipe for steel receivers, but I can't find them

### ISSUE THREAD

**Issue by NineDivinez** [pWn3d1337/Techguns#18]
Just like the title, I need a recipe that I can't find and NEI won't show it to me, nor does your wiki.  If you could get me that recipe, that'd be fantastic, thanks :)

**Comment by pWn3d1337** [comment]
NEI will show the receipe, except you don't have the required items. If you don't have a mod that adds steel. It does not work.

**Comment by pWn3d1337** [comment]
You can also enable steel crafting by resmelting iron in the Techguns config when you do not want to use another mod for it.

**Comment by NineDivinez** [comment]
Ok thanks.  What mods do I need for that to work?  what is the recomended?

**Comment by pWn3d1337** [comment]
Thermal foundation adds many ores. Everything but steel. Steel gets added by mekanism, railcraft ... . You can enable steel in the techguns config. Mekanism may need to add nuggets in the techguns config.
