### ISSUE TITLE
mod has a "fatial" error when minecraft is launched

### ISSUE THREAD

**Issue by Monoploxy01** [pWn3d1337/Techguns#182]
I have Minecraft forge 1.7.10 installed I downloaded chisel and techguns for 1.7.10 but everytime I launch the game I get this error message: The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: techguns/items/OreClusterScanner

**Comment by pWn3d1337** [comment]
Required mods not installed, read description
