### ISSUE TITLE
Can't create fabricator without having a fabricator?

### ISSUE THREAD

**Issue by psyon** [pWn3d1337/Techguns#19]
The recipe for the Fabricator Housing requires Cybernetic Parts, which can only be made in the Fabricator.  Are the Cybernetic Parts supposed to be a mob drop or something you can loot from structures?  I haven't been able to find them anywhere.

**Comment by pWn3d1337** [comment]
They drop from cyberdemons in the nether. The helicopter also drops them, but that might change in the future.
