### ISSUE TITLE
Crash when shooting techguns entity with flans mod gun

### ISSUE THREAD

**Issue by Sav4g3** [pWn3d1337/Techguns#190]
First I would like to state that im not sure if this is the right place to put this. But I run a small minecraft community and we wanted to run techguns with flans but we encountered an where when you shoot a techguns mob with a flans gun the server would crash
[crash-2018-07-15_04.17.01-server.txt](https://github.com/pWn3d1337/Techguns/files/2195667/crash-2018-07-15_04.17.01-server.txt)
.

**Comment by pWn3d1337** [comment]
that's a bug with sponge, it should be fixed in the next version.
