### ISSUE TITLE
Request: Turret Line of Sight

### ISSUE THREAD

**Issue by Golrith** [pWn3d1337/Techguns#202]
Turrets are quite happy firing away at mobs in caves or behind hills. Is there any way to give them line of sight so they are not wasting time firing away at blind spots?

**Comment by pWn3d1337** [comment]
They do check line of sight, it's minecraft mob AI.

**Comment by Golrith** [comment]
Unfortunately it's not working, as they are trying to shoot mobs they cannot see.
But, now you've mentioned it's Minecraft Mob AI, let me do some experiments, I had a couple of mods that change the mob AI which allows mobs to "see" through blocks within a radius, it might be they are inadvertently being affected too.

**Comment by pWn3d1337** [comment]
Techguns turrets are NPCs and are based on mojangs mob AI.

**Comment by Golrith** [comment]
Confirmed, it was an issue of another mod changing AI. I adjusted settings, and now turrets cannot see mobs behind blocks.

Great mod BTW, loving the models & effects.
