### ISSUE TITLE
(Cross-Mod Problem) Werewolves Cannot Into Guns Without Crashing People

### ISSUE THREAD

**Issue by BSRaven** [pWn3d1337/Techguns#217]
As title says - anyone attempting to view a Howling Moon werewolf using a TechGun gun (even the wolf themselves in 3rd person) gets a hard crash. Replicated with and without FoamFix and BetterFPS.

Log here: https://pastebin.com/vBz81ubS

**Comment by pWn3d1337** [comment]
Moved to 1.12 tracker:
https://github.com/pWn3d1337/Techguns2/issues/85
