### ISSUE TITLE
TechGun nether lag issues with thaumcraft

### ISSUE THREAD

**Issue by d1kong2** [pWn3d1337/Techguns#22]
cant realy be to specific, just wanted to say that in my modpack im runing into weird giant heaps of lag when in the nethere but only in specific areas and i cant tell why, it often ends up crashing when it happens and the only happens when this mod is installed with thaumcraft. if i figure it out any more or actualy get a crash report i will post it here. output mentions an entity tracking issue if that helps.

**Comment by pWn3d1337** [comment]
I need the exact crash log or console output. I have seen a problem once where a lot of mobs spawned in the nether and the sever totally lagged, but it was a big modpack and I could not directly find a connection to techguns.

**Comment by d1kong2** [comment]
once i removed thaumcraft the issue stoped occuring. I never had a crash log nor did the game ouptut say anything intresting besides entity tracking error. The problem only happened when both thaumcraft and tehguns where installed but honestly i dont know what else to tell you. When it came down to it i picked your mod over thaumcraft. 
Cheers! 

----- Original Message -----
