### ISSUE TITLE
Compatibility with draconic evolution mod

### ISSUE THREAD

**Issue by Libright1558** [pWn3d1337/Techguns#222]
Techguns' weapons can bypass draconic evolution armor's shield which is supposed to block damage.

minecraft version : 1.12.2
draconic evolution mod version : 1.12.2-2.3.20.333-universal 
techguns mod version : 2.0.1.2_1

**Comment by Libright1558** [comment]
Is that intentional or just a Bug ?

**Comment by pWn3d1337** [comment]
If mod A changes things and mod B changes thing the results are unpredictable. There is no specific code that somehow tries to bypass it. I would call it a "compatibility conflict". Very likely the damage bypass that techguns uses for the different damage types is incompatible with whatever draconic evolution does.
