### ISSUE TITLE
Hangar Doors Do not work with Redstone

### ISSUE THREAD

**Issue by voidswrath** [pWn3d1337/Techguns#223]
As title says hangar doors are not working with redstone.

Edit: this is all doors with techguns

Version: techguns-1.12.2-2.0.1.2_1

Side Request: Make an option to change doors to not automatically close? Possible shift right clicking with a wrench or hammer item.

**Comment by pWn3d1337** [comment]
They do work, and you can config them when you shift+right click the door with a crowbar.

**Comment by voidswrath** [comment]
Yep you are right sorry about that. Appreciate the quick response. I'm curious if there is a way I can middle mouse a door that has some changed configs and place it without having to readd those changes.
