### ISSUE TITLE
Portal Item ID

### ISSUE THREAD

**Issue by oryfoxer7410** [pWn3d1337/Techguns#23]
Close Portals after time limit. 

Is there a way to have life of the portal limited to a specific amount of time? 

I want to automatically have opened portals removed after a few minutes on my server. What is the item ID for the portal that is generated so I can have them close after a specific time using a plugin?

**Comment by pWn3d1337** [comment]
Portals? what portals? This mod has no portals.

**Comment by oryfoxer7410** [comment]
delete this, wrong git.
