### ISSUE TITLE
Machines won't take fluids directly or from pipes.

### ISSUE THREAD

**Issue by TheSpiderDungeon** [pWn3d1337/Techguns#232]
None of the machines that require fluids (chem lab, reaction chamber, etc) will take fluids no matter what I try, survival or creative. Won't take fluids from buckets, from mekanism or erebus pipes, from the mekanism tanks, nothing. It takes power just fine, and I can add items into the machines, just not fluids.
Below is the reaction chamber setup in creative, but the same thing happened with the chemical lab as well.

I've already checked with an updated version, and it didn't help.
![image](https://user-images.githubusercontent.com/14132982/59810981-3ae51f00-92de-11e9-8c8c-f2d4db6cf4c5.png)
(Power is being pumped in from the floor above)

**Comment by pWn3d1337** [comment]
There is no fluid in the pipe, you need to tell the tank to output it to the pipe. Also the reaction chamber has a liquid level slider and only takes 1 bucket per liquid level (shown as red line on the tank). Make sure you increase the liquid level and that there is liquid in the pipe.

**Comment by TheSpiderDungeon** [comment]
Yeah I know about the liquid level slider; I matched the recipe gui exactly, but it still didn't work. I assumed it was a Techguns issue because I couldn't use buckets on any of the machines either. When I used the mod a good few months back, I was able to use a bucket directly on the chem lab. Now, apparently I can't do that anymore. Maybe due to all the mod changes, but I have no idea. I also tried looking at the wiki for the pipes and still couldn't figure it out; Either I'm dumb or the documentation is bad. Probably the former if I'm being honest.

Would you say this is a Mekanism problem? Maybe it's the pipe itself.

EDIT: For people in the future with this problem, the Mekanism wiki says this, which I missed earlier:

> 'Shift-Right-clicking' the tank with a Configurator will set it to auto-output, as indicated by the input and output ports colour changing to green.

**Comment by erayerts** [comment]
Same problem happened to me on October 2021, anyone solved that ?

**Comment by TheSpiderDungeon** [comment]
> 
> 
> Same problem happened to me on October 2021, anyone solved that ?

I already posted the fix.

**Comment by erayerts** [comment]
> > Same problem happened to me on October 2021, anyone solved that ?
> 
> I already posted the fix.

The problem was about the pipes (from another mod), problem solved, thanks anyways.

**Comment by KAMRAN5555** [comment]
I am able to import fluids into the reaction chamber but not able to export them, the liquid just disappears as I reduce the liquid level slider the fluid in the chamber also reduces but does not collect in any of the pipes or container's, I have used enderIO, Immersive engineering, thermal expansion and also extra utilities 2, but the liquid just does not collect after removing from the chamber, is it not supported in Minecraft 1.12.2 TechGuns or I am not doing it right?

I have seen tutorials where people collect the fluids after the recipe is done
