### ISSUE TITLE
game crash on shooting (no flans)

### ISSUE THREAD

**Issue by MitchMitch123** [pWn3d1337/Techguns#233]
As the title says, the game crashes when I fire a weapon. This is the line I get back from minecraft once the game crashes, having trouble understanding what the rest of the crash report is trying to tell me though.
java.lang.NoSuchMethodError: elucent.albedo.event.GatherLightsEvent.getLightList()Ljava/util/ArrayList;

[crash-2019-06-25_12.55.48-client.txt](https://github.com/pWn3d1337/Techguns/files/3323363/crash-2019-06-25_12.55.48-client.txt)

**Comment by TheSpiderDungeon** [comment]
Try removing the Albedo mod. It tends to not play well with a lot of mods.

**Comment by pWn3d1337** [comment]
The newer version of albedo has changed the api and is incompatible with the current techguns releases, this will be fixed next version.

**Comment by MitchMitch123** [comment]
> The newer version of albedo has changed the api and is incompatible with the current techguns releases, this will be fixed next version.



> Try removing the Albedo mod. It tends to not play well with a lot of mods.

Thanks guys, fixed the issue I was having!
