### ISSUE TITLE
Nightvision not working

### ISSUE THREAD

**Issue by UserFucksticks** [pWn3d1337/Techguns#238]
The nightvision goggles do not do anything, i'm running the latest version of 1.12.2, charged up my goggles and equipped them into my face slot, pressed the nightvision hotkey and cannot notice any change in how bright a dark place is

**Comment by pWn3d1337** [comment]
they apply the nightvision potion effect, Show me a screenshot of your techguns inventory tab.

**Comment by UserFucksticks** [comment]
I deleted the original world, and had to recreate the situation, so it may not reflect the original problem I had, perhaps it's the shader-pack that im running? (SEUS_renewed), but the effect does not work inside of caves
![2019-07-28_14 31 03](https://user-images.githubusercontent.com/45144251/62011891-5eed1900-b144-11e9-987f-45a37bd9b4e2.png)

**Comment by UserFucksticks** [comment]
![2019-07-28_14 32 01](https://user-images.githubusercontent.com/45144251/62011899-7cba7e00-b144-11e9-90d7-dd63dc562eee.png)
it works just fine outside, though

**Comment by UserFucksticks** [comment]
SEUS_renewed, does in fact, cause my nightvision to stop working
