### ISSUE TITLE
Suggestions about the Minetweaker Support Tab

### ISSUE THREAD

**Issue by truemogician** [pWn3d1337/Techguns#254]
![QQ图片20200303225244](https://user-images.githubusercontent.com/33447608/75787462-bc63db00-5da1-11ea-96b9-d56f27a37842.png)
To start with, I have to express my appreciation and admiration for you marvelous work,  the weapons provided by Techguns remain my favorate even after experiencing quite a few other science or adventure mods. The textures of those guns and projectiles are just awesome!
Recently I was asked to set up a server with a famous modpack. Unfortunately Techguns isn't involved. Due to my preferrence, I decided to manually add it in;
For balance, the damage needs to be changed. However, you Minetweaker Support page missed the part about gunstats setting, and no other websites have ever mentioned about it. But through decompiling I found that you've actually provided a way for MineTweaker to edit the gunstats and amorstats. 
Thus it's suggested that you added this part into the Minetweaker Support tab, which will help other modpack makers facing the same troubles.

**Comment by pWn3d1337** [comment]
https://github.com/pWn3d1337/Techguns2/wiki/Crafttweaker-Weapon-Armor-stats

That page already exists, you just missed it.
