### ISSUE TITLE
Problems with Anti Gravity Core

### ISSUE THREAD

**Issue by redstonek** [pWn3d1337/Techguns#256]
Anti Gravity Core in the newest 1.12.2 version is impossible or insanely hard to craft, because of the constantly changing focus. Please fix that.

**Comment by PoopyPantsMan** [comment]
did you find a solution? its still impossible for me to get it without the chamber exploding.

**Comment by redstonek** [comment]
I don't remember exactly what i did, but i think i just used a more powerful method of powering the machine (using some other mod). Anyways I lost most of the interest in messing with mods and the development of the mod seems to be dead.
