### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by Mihawka** [pWn3d1337/Techguns#27]
If one has your mod and TheCamping mod the inventory tab can not open :(
Sorry for my bad english im french.

**Comment by pWn3d1337** [comment]
Because the other mod replaces the default inventory. Look if it has a config/keybind to access the default inventory. Techguns does not replace the default inventory, it just adds a button to open the techguns ui.

**Comment by Rezoseansstudios** [comment]
WELL I CANT PLAY IT BECAUUUUSE I MIGHT NEED A CORE

**Comment by pWn3d1337** [comment]
No interaction since a long time, no a techguns bug anyway, closed.
