### ISSUE TITLE
Structure Spawning

### ISSUE THREAD

**Issue by RogueWarrior76** [pWn3d1337/Techguns#3]
I've been playing around with this mod in my custom pack for a few days now. And so far the only complaint I have is that structures are spawning way too frequently. I started a new world last night and flew around spawn for like 10 minutes and encountered 5 of the military bases. I see no option in the config to turn down the frequency of these.

**Comment by pWn3d1337** [comment]
Yes, there is only a boolean for on/off currently, I will add settings for frequency in next update. (There will also be new structures)

**Comment by RogueWarrior76** [comment]
Ok thanks

**Comment by pWn3d1337** [comment]
I added config values for spawning. There is now a SpawnweightSmall and a SpawnweightBig value. These are chunkCoords, If a chunkx and chunkz modulo the spawnweight is zero it's tried to spawn a building. Small is for the smaller buildings, big for military base (currently only big). In the current released version it's hardcoded to 8(small) and 16(big). These 2 values can now be set in the config file.

In the next version this will be included.
