### ISSUE TITLE
Player "Animation" Problem

### ISSUE THREAD

**Issue by DerLeon2017** [pWn3d1337/Techguns#34]
Hi, my problem is, when i hold a gun my arms are still normal and the gun points at the ground. This doesn't affect the gamplay or gun handling but it looks really weird. I have a few other mods, but none of them should affect the player. Please help

**Comment by pWn3d1337** [comment]
You have another mod that does something with animations. Everytime someone had a problem like that it was another mod changing animations. Post you modlist.

**Comment by DerLeon2017** [comment]
Securitycraft, adventure backpacks, ae2stuff, Applecore, ae2, archimedesships, asielib, backpack, baublesstuff, bdlib, betterfps, betterstorage, bibliocraft, BigReactors, BiomesOPlenty, buildcraft, chickenchunks, chisel, codechickencore, cofhcore, craftingPillars, craftingtweaks, damage-indicators, decocraft, dense-ores, MoCreatures, emerald-obsidian-armor, emotes, enchantingPlus, Endercore, EnderIO, EnderStorage, Ex-Nihilo, fastcraft, FastLeafDecay, FPSplus, FusionWarfare, Gravestone, Hats, hbm nuclear tech, IChunUtil, ImmersiveEngineering, Inventory Tweaks, ironchest, IvToolkit, LootBags, malisis core, malisis doors, Mantle, Mekanism and Addons, Minefactory Reloaded, moving world, neiaddons, NEIIntegrations, NoMoreRecipeConflicts, NEI, Nuclearcraft, OpenModsLib, OpenModularTurrets, Optifine, Pam's Harvestcraft, Planetguylib, PlayerAPI (because i thought this would fix it), Project Red- Everything, Psychedelicraft, Railcraft, RedstoneArsenal, SimplyJetpacks, Solarflux, Statues Mod, Storage Drawers, Fisk's Superheroes, TConstruct, Techguns, Thermal Dynamics, Thermal Expansions, Thermal Foundations, TiCTooltips, TMechworks, UpdateChecker, Veinminer, Waila, Waila Harvestability, WAILAPlugins, weaponcaseloot, and Xaero's Minimap.


And thats one of my smaller Modpacks

**Comment by pWn3d1337** [comment]
Player API won't help. I don't know all of that mods so hard to say. Can you post a screenshot of the problem?

**Comment by DerLeon2017** [comment]
![2017-01-29_14 18 20](https://cloud.githubusercontent.com/assets/25402816/22404287/db982fb0-e62d-11e6-8dc2-db7a5c6a5db3.png)

**Comment by pWn3d1337** [comment]
Very likely another mod interfering.

**Comment by DerLeon2017** [comment]
Ok, i'm going to have a look at it again.

**Comment by DerLeon2017** [comment]
Fixed it, i removed some Mods: adventure backpacks, emotes, fusion warfare, hats, Psychedelicraft(IvToolkit), Statues mod(AsieLib) and Fisk's Superheroes

**Comment by pWn3d1337** [comment]
I think it could be one of those: fusion warfare, Fisk's Superheroes or emotes.

**Comment by pWn3d1337** [comment]
I just looked at emotes, very liked that was causing the problem.

**Comment by DerLeon2017** [comment]
Ok thanks, it was
