### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by SwagSchool101** [pWn3d1337/Techguns#38]
Two issues, not sure if they are both connected.

1. Whenever we place a flag on a server it makes us disconnect.

2. Whenever we try to switch to another section of the inventory, Minecraft crashes, with the following report.

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2/5/17 6:54 PM
Description: Rendering item

java.lang.NullPointerException: Rendering item
	at net.minecraft.item.ItemStack.func_94608_d(ItemStack.java:123)
	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:161)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:929)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:760)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemStack.func_94608_d(ItemStack.java:123)
	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:161)

-- Item being rendered --
Details:
	Item Type: null
	Item Aux: ~~ERROR~~ NullPointerException: null
	Item NBT: null
	Item Foil: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:929)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:760)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (553, 154). Absolute: (1106, 748)
	Screen size: Scaled: (929, 529). Absolute: (1858, 1057). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['HighFyi'/2685, l='MpServer', x=238.49, y=74.65, z=-102.75]]
	Chunk stats: MultiplayerChunkCache: 370, 370
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (240,64,-100), Chunk: (at 0,4,12 in 15,-7; contains blocks 240,0,-112 to 255,255,-97), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 29850 game time, 29850 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 31 total; [EntityClientPlayerMP['HighFyi'/2685, l='MpServer', x=238.49, y=74.65, z=-102.75], SkeletonSoldier['Skeleton Soldier'/3712, l='MpServer', x=210.50, y=38.00, z=-118.50], EntityCow['Cow'/67, l='MpServer', x=249.25, y=67.00, z=-135.81], EntityCreeper['Creeper'/3715, l='MpServer', x=202.50, y=43.00, z=-115.50], EntityCow['Cow'/68, l='MpServer', x=238.91, y=68.00, z=-134.91], EntityCow['Cow'/69, l='MpServer', x=233.81, y=67.00, z=-133.81], EntityCow['Cow'/70, l='MpServer', x=253.88, y=68.00, z=-130.84], ZombieFarmer['Zombie Farmer'/2763, l='MpServer', x=213.50, y=40.00, z=-99.50], ZombieMiner['Zombie Miner'/3661, l='MpServer', x=213.50, y=61.00, z=-132.50], Bandit['Bandit'/3664, l='MpServer', x=177.50, y=57.00, z=-58.50], ZombieSoldier['Zombie Soldier'/3792, l='MpServer', x=211.50, y=40.00, z=-89.50], ZombieSoldier['Zombie Soldier'/3217, l='MpServer', x=211.50, y=43.00, z=-118.50], ZombieFarmer['Zombie Farmer'/3538, l='MpServer', x=214.50, y=40.00, z=-98.50], ZombieMiner['Zombie Miner'/3794, l='MpServer', x=211.50, y=40.00, z=-91.50], ZombieMiner['Zombie Miner'/3869, l='MpServer', x=204.50, y=35.00, z=-114.50], EntityItem['item.item.seeds'/2463, l='MpServer', x=276.31, y=67.13, z=-110.34], ZombieFarmer['Zombie Farmer'/3743, l='MpServer', x=277.50, y=48.00, z=-67.50], ZombieFarmer['Zombie Farmer'/3871, l='MpServer', x=209.03, y=33.00, z=-116.41], ZombieFarmer['Zombie Farmer'/3745, l='MpServer', x=276.50, y=48.00, z=-67.50], ZombieMiner['Zombie Miner'/3873, l='MpServer', x=206.44, y=33.00, z=-115.50], ZombieFarmer['Zombie Farmer'/3747, l='MpServer', x=279.50, y=48.00, z=-66.50], ZombieMiner['Zombie Miner'/3493, l='MpServer', x=212.50, y=43.00, z=-119.50], ZombieFarmer['Zombie Farmer'/3368, l='MpServer', x=210.50, y=39.00, z=-104.50], ZombieFarmer['Zombie Farmer'/3761, l='MpServer', x=249.50, y=27.00, z=-130.50], ZombieFarmer['Zombie Farmer'/3763, l='MpServer', x=246.50, y=27.00, z=-129.50], EntityItem['item.item.seeds'/2488, l='MpServer', x=260.41, y=69.13, z=-95.47], SkeletonSoldier['Skeleton Soldier'/3832, l='MpServer', x=215.50, y=34.00, z=-74.50], ZombieSoldier['Zombie Soldier'/3771, l='MpServer', x=224.50, y=40.00, z=-130.50], ZombieFarmer['Zombie Farmer'/3773, l='MpServer', x=224.50, y=40.00, z=-127.50], ZombieMiner['Zombie Miner'/3263, l='MpServer', x=260.50, y=49.00, z=-81.50], ZombieSoldier['Zombie Soldier'/3775, l='MpServer', x=224.50, y=40.00, z=-126.50]]
	Retry entities: 0 total; []
	Server brand: cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 505253752 bytes (481 MB) / 1037565952 bytes (989 MB) up to 1037565952 bytes (989 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx1024m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 23 mods loaded, 23 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (modpack.jar) 
	UCHIJA	Forge{10.13.4.1558} [Minecraft Forge] (modpack.jar) 
	UCHIJA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJA	OpenComputers|Core{1.6.1.10} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHIJA	catwalks{2.0.1} [Catwalks Mod] (Catwalks-2-Mod-1.7.10.jar) 
	UCHIJA	catwalkmod{x.x.x} [Legacy Catwalk Compat] (Catwalks-2-Mod-1.7.10.jar) 
	UCHIJA	Chimneys{1.7.2} [Chimneys] (Chimneys-Mod-1.7.10.jar) 
	UCHIJA	chisel{2.9.4.10} [Chisel] (Chisel-2.9.4.10.jar) 
	UCHIJA	coffin{1.0} [Coffin Mod] (Coffin-Mod-1.7.10.jar) 
	UCHIJA	examplemod{1.0} [Example Mod] (Coffin-Mod-1.7.10.jar) 
	UCHIJA	fairylights{1.4.0} [Fairy Lights] (fairylights-1.4.0-1.7.10.jar) 
	UCHIJA	lootbags{2.0.16} [Loot Bags] (LootBags-1.7.10-2.0.16.jar) 
	UCHIJA	NuclearCraft{1.9e} [NuclearCraft] (NuclearCraft-1.9e--1.7.10.jar) 
	UCHIJA	OpenComputers{1.6.1.10} [OpenComputers] (OpenComputers-MC1.7.10-1.6.1.10-universal.jar) 
	UCHIJA	openradio{0.6.1} [OpenRadio] (OpenRadio-0.6.1.jar) 
	UCHIJA	SonarCore{1.1.1} [SonarCore] (SonarCore-1.7.10-1.1.1.jar) 
	UCHIJA	PracticalLogistics{0.1.9} [Practical Logistics] (Practical-Logistics-1.7.10-0.1.9.jar) 
	UCHIJA	RouterReborn{1.1.9} [Router Reborn] (Router-Reborn-Mod-1.7.10.jar) 
	UCHIJA	Techguns{0.1.0} [Techguns] (Techguns.beta.1.1.1.jar) 
	UCHIJA	vending{1.2.3} [vending] (Vending-Block-Mod-1.7.10.jar) 
	UCHIJA	WorldTooltip{1.0.16} [WorldTooltip] (WorldTooltip-1.7.10-1.0.16-51.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.39' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:OFF, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:ON, PneumaticCraft:OFF
	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.39, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by pWn3d1337** [comment]
**Whenever we place a flag on a server it makes us disconnect.**
The flag should not be placed by hand, it also no longer appears in creative inventory.

Techguns{0.1.0} [Techguns] (**Techguns.beta.1.1.1.jar**)
This is not the newest version. Update.

**Comment by SwagSchool101** [comment]
Still Crashes for me with the same error.

**Comment by pWn3d1337** [comment]
The posted error has no direct reference to techguns. Could be something else too. It crashes on creative menu.
I noticed one more thing. Use a newer version of chisel, use 2.9.5.11. This is the one I used for compiling against.
https://minecraft.curseforge.com/projects/chisel/files/2287442

**Comment by pWn3d1337** [comment]
No interaction for longer than a month, closed.
