### ISSUE TITLE
Generation Crash with Alphatest 2

### ISSUE THREAD

**Issue by Fortist** [pWn3d1337/Techguns#42]
http://pastebin.com/9HnrPNbp

Disabling the structure spawning fixes this issue.

**Comment by pWn3d1337** [comment]
It crashes while trying to load a building definition from a textfile that is within the jar. Buildings for Worldgen are loaded that way in the previous versions too. Did you ever use the 1.1.3 version of Techguns?

**Comment by Fortist** [comment]
I did.
But I think I see the problem. 
Was messing with the sounds since a lot of them are too loud for headphones, and I didnt move over all the files from one .jar to another. (an Obtuse way of changing sounds, I know)
