### ISSUE TITLE
enh.. weapons

### ISSUE THREAD

**Issue by Cronosus** [pWn3d1337/Techguns#5]
hello
know you Mass Effect? nice weapons too.. :)
and i'll be very thankful, if you add weapons from Stargate (Zat', Staff.. etc). :)
http://i1184.photobucket.com/albums/z336/alaskajedi/Sporcle%20Quiz%20Photos/stargatehandheldweapons-1.png

and maybe armors too? (jaffas armors are great)

**Comment by Cronosus** [comment]
Implemented or declined?

**Comment by pWn3d1337** [comment]
It's a bug tracker and I wanted to clean up.  I can't add that many stuff, I don't have time for that.

**Comment by Cronosus** [comment]
and what about just Staff Weapon and Zat?
