### ISSUE TITLE
Launch Problem

### ISSUE THREAD

**Issue by Mobslayer3002** [pWn3d1337/Techguns#51]
Hello I have a problem when I start this mod. It loads, crashes, and then gives me this error: Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: techguns/items/OreClusterScanner. How do I fix?

**Comment by pWn3d1337** [comment]
Install the required mods. Chisel and CofhLib are needed.

**Comment by Mobslayer3002** [comment]
Alright so I downloaded the Chisel mod but I can't acess CofhLib. When I go to the curseforge page for it, it says page not found. Can you link another source?

**Comment by pWn3d1337** [comment]
links work fine for me:

https://minecraft.curseforge.com/projects/cofh-lib/files
