### ISSUE TITLE
Bunker door duplication.

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [pWn3d1337/Techguns#52]
When you break upper part of bunker door, it will drop two door items.
![2017-04-06_03 30 53](https://cloud.githubusercontent.com/assets/5104603/24733741/b4091c40-1a79-11e7-9a81-8626fb56b843.png)
![2017-04-06_03 30 55](https://cloud.githubusercontent.com/assets/5104603/24733745/b66f1322-1a79-11e7-88cd-24c588e70770.png)

Mod version: Techguns.beta.1.2_Alphatest2

**Comment by pWn3d1337** [comment]
That was an easy fix, should work now and will be in the next released version.
