### ISSUE TITLE
Akimbo weapons duplication.

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [pWn3d1337/Techguns#54]
When you split akimbo guns with shift-click, crafting result will give stack with two guns instead of the one and another one after crafting.

![2017-04-06_03 45 04](https://cloud.githubusercontent.com/assets/5104603/24734057/b1b6d7be-1a7b-11e7-8dd9-e85741122f01.png)
![2017-04-06_03 45 05](https://cloud.githubusercontent.com/assets/5104603/24734059/b324aac2-1a7b-11e7-895c-9d8e1b4e853a.png)

Mod version: Techguns.beta.1.2_Alphatest2

**Comment by pWn3d1337** [comment]
I could not find another way to fix this than setting the stack size to 1. You still get two guns, it just does not display as 2 at recipe. Not perfect, but better than duping. I will see if I find a better solution.
