### ISSUE TITLE
Needs A Resource for the third slot- Ammo Press

### ISSUE THREAD

**Issue by TheDarkNinja56** [pWn3d1337/Techguns#55]
Ammo press doesn't work because it needs a 3rd material.

**Comment by pWn3d1337** [comment]
It does require 3 materials: 
Slot 1:  Lead/Steel
Slot 2: gunpowder
Slot 3: iron/copper/tin... many other metals are allowed.

If you don't have lead or steel, enable it in the techguns config or use another mods that has them like Mekanism, or Thermal Expansion + Tinkers construct.
