### ISSUE TITLE
Frag grenade no recipe yet?

### ISSUE THREAD

**Issue by CKTheUltimate** [pWn3d1337/Techguns#57]
There's no recipe for frag grenade now,is this a bug of Not Enough Items or it isn't implemented yet?

And btw when will this mod add ways for hostile mobs(bandits,cyberdemons,alien bug, etc )to spawn?Currently there's no way for these awesome mobs to spawn naturally.

**Comment by pWn3d1337** [comment]
Bandits do spawn naturally, just not directly at the world spawn so you don't get rekt in the first night. Cyberdemons spawn in the nether. Alien bugs spawn in alien bug nests, which can generate in deserts. So all 3 do spawn.
 
Frag grenades will get a recipe in the next version.

**Comment by CKTheUltimate** [comment]
thx
