### ISSUE TITLE
Every hostile mob burns when it's day(alpha 2)

### ISSUE THREAD

**Issue by CKTheUltimate** [pWn3d1337/Techguns#62]
Every hostile mobs burns like normal zombies when it's day, before it won't burn,please change this back this in the next beta plz.

**Comment by pWn3d1337** [comment]
Really? I did not change this and never noticed...

**Comment by CKTheUltimate** [comment]
When I first played the mod last year,I tested the guns by spawning in soldiers during the day, they won't burn.But now they burns and ruin the game as I can simply raid the camps during the day without anyone stopping.

**Comment by pWn3d1337** [comment]
They should not burn. I will check this.

**Comment by pWn3d1337** [comment]
I checked it, they do not burn.

**Comment by CKTheUltimate** [comment]
Is it the problem of the config?I tested it several times with different worlds but every mob is still burning

**Comment by CKTheUltimate** [comment]
Wait...everything stops burning now...Every time I solve the problems of this mod by repeated testing...Sorry for wasting time again...
