### ISSUE TITLE
Missing gun slot in turret base blocks?

### ISSUE THREAD

**Issue by cyris69** [pWn3d1337/Techguns#63]
So I'm running the most recent release for 1.7.10 and my base blocks have two red and two blue slots plus area for 9 ammo stacks. Wanted to see if this is a glitch/error or was removed because would like some chainsaw bases.

**Comment by pWn3d1337** [comment]
The turret base wasn't changed... o.0 can you post a screenshot please?

**Comment by cyris69** [comment]
I'm so sorry, I completely forgot I installed open modular turrets as well. You can remove this post, again, very sorry for posting without looking more closely. I've been playing with both apparently for about a month and never thought about it until now. Either way, great mod, and super fast response time.
