### ISSUE TITLE
Smart Moving Compatability

### ISSUE THREAD

**Issue by SanokKule** [pWn3d1337/Techguns#67]
Is there is any way to make them work together?
Jetpack for example
![image](https://cloud.githubusercontent.com/assets/24497821/25578521/a2855004-2e80-11e7-84b4-2466916b6a7d.png)
![image](https://cloud.githubusercontent.com/assets/24497821/25578535/bf475426-2e80-11e7-91b7-a1912c74e978.png)

It is not moving with player

**Comment by pWn3d1337** [comment]
Mods that change animations don't work well with techguns.

**Comment by SanokKule** [comment]
So can you do something with that?

**Comment by pWn3d1337** [comment]
I don't have the time to add compatibility for every other mod.
