### ISSUE TITLE
Double drop

### ISSUE THREAD

**Issue by LemADEC** [pWn3d1337/Techguns#74]
As of Techguns.beta.1.2_alphatest3, you can get free resources by breaking a multiblock controller while picking up its content.

Also, slots aren't validating their content, so we can put any item blocks/items in the GUI and get free extras due to this bug.

**Comment by pWn3d1337** [comment]
Not reproducable, please explain exactly what you did.

**Comment by LemADEC** [comment]
Place valueable items in the GUI
Player A open the GUI, ready to shift click items out
Player B break the blocks
At the same time as the break happens, player A remove the items

Observed: items are on the floor and in player A inventory
Expected: only one set of items

It's all about synchronization. You should be able to do it as a single player using a block breaker and some simple redstone to delay it.

Possible root-causes include:
- GUI not closed right when block is broken
- GUI not checking if block is still there before giving token
- GUI not removing the items before transferring them
- Items dropping before closing the GUI
- etc.

**Comment by pWn3d1337** [comment]
Not reproduceable with a block breaker in single player.

I discovered another bug with multiblocks that caused problems when the controller was broken and replaced at the same spot, the slave tile entities still had cashed the old object and would send power/items there. Maybe this could have been the issue. I will try again with dedicated server.

**Comment by LemADEC** [comment]
Do you have a new build we could try with?

**Comment by pWn3d1337** [comment]
https://minecraft.curseforge.com/projects/techguns/files/2429219

**Comment by pWn3d1337** [comment]
Can you still do the dupe with this version?

**Comment by LemADEC** [comment]
looking good so far, checking the explosives now

**Comment by LemADEC** [comment]
multiblock dup is fixed, thanks!
