### ISSUE TITLE
Aircraft carrier generation crash

### ISSUE THREAD

**Issue by maieeleene** [pWn3d1337/Techguns#78]
[crash-2017-06-12_16.13.29-server.txt](https://github.com/pWn3d1337/Techguns/files/1067634/crash-2017-06-12_16.13.29-server.txt) or https://pastebin.com/fF4JKVJp
Hello, i have this crash all the time when an aircraft carrier gets into world generation. After that, it generates cut in half according to chunk border.

**Comment by pWn3d1337** [comment]
Strange, that's a call to world.setBlock that seems to cause the crash, do you have some kind of worlborder plugin or something?

**Comment by maieeleene** [comment]
Not at all, i have some more crashlogs if you're interested, i'm not sure they'll differ much. 
https://pastebin.com/zynafwns
https://pastebin.com/wTy8cTjd

**Comment by pWn3d1337** [comment]
It's the same code location, but I still don't know why it happens.

**Comment by maieeleene** [comment]
Gosh, i'm stupid. I had aluminium disabled in chisel config. Sorry.

**Comment by maieeleene** [comment]
Thank you for such a great piece of modded minecraft by the way. Keep it up.

**Comment by pWn3d1337** [comment]
That explains it. The block was null.
