### ISSUE TITLE
How to access Techguns inventory tab in Creative?/ white screen while scoping

### ISSUE THREAD

**Issue by Isaac96** [pWn3d1337/Techguns#82]
I can't access the Techguns inventory tab in Creative mode. 
Additionally, when I use the scope on a sniper, the screen goes all white. I have a slightly older version of Techguns, so I will update ASAP.

**Comment by pWn3d1337** [comment]
techguns inventory can't be accessed in creative currently. And the sniper scope problem must be something on your end. Shader mod? Optifine?

**Comment by Isaac96** [comment]
No, just Forge 1.7.10. It is probably just the old version of Techguns that I have. It is about 5 months old. I'll update soon. :) My render distance is set at 2 chunks ATM.

**Comment by pWn3d1337** [comment]
I don't think so, the scope has always worked.

Is your PC very weak? maybe it can't handle it.

**Comment by Isaac96** [comment]
It is working now for some reason. It must have been something in the config files. Thanks!
