### ISSUE TITLE
Powered Armor, Clear Inventory

### ISSUE THREAD

**Issue by SymbioticMutant** [pWn3d1337/Techguns#9]
Two slight issues:

- Powered armor does not work with {Unbreakable:1} data tag
  The power in the suit is at 0 with this data tag but consumes all energy cells in the inventory without adding its effects

- Clearing inventory does not clear the alt. inventory slots
   Ammo in the other inventory slot in survival along with others does not clear with the /clear command

**Comment by pWn3d1337** [comment]
I will look into it. I never really checked enchants. 1) I don't think that's really the case, the power is saved as an own NBT tab, durability is independent of power.  That behaviour you mentioned would happen when the energy tag is not added to the armor on spawning. I had that once when spawning it out of NEI. Crafting/creative has the tag correctly set.

**Comment by SymbioticMutant** [comment]
Ah, that explains the first "issue", thank you. Best of luck to you on resolving the second.

I just have one question then: What data tag is added automatically when spawning in the armour in creative mode? Is it {Power:#} with a numerical value assigned (in place of #)?

**Comment by pWn3d1337** [comment]
Two nbt tags of type integer are added for power: "power" and "maxpower". Also "camo" is added as byte, when you change the camo, but it doesn't have to be there. no camo tag = default camo. 

Usually it works when spawned from NEI too. 


`@Override
	public void onCreated(ItemStack stack, World world, EntityPlayer player) {
		super.onCreated(stack, world, player);
		NBTTagCompound tags = stack.getTagCompound();
		if(tags==null){
			tags=new NBTTagCompound();
			stack.setTagCompound(tags);
		}
		tags.setInteger("power", 0);
		tags.setInteger("maxpower", this.maxpower);
	}`

**Comment by pWn3d1337** [comment]
Invetory clearing doesn't work. Forge seems not to have a hook for it.
